# permissions for end users to view healthchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rollout-controller
    app.kubernetes.io/managed-by: kustomize
  name: healthcheck-viewer-role
rules:
- apiGroups:
  - kuberik.com
  resources:
  - healthchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberik.com
  resources:
  - healthchecks/status
  verbs:
  - get
