# This rule is not used by the project release-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kuberik.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: release-controller
    app.kubernetes.io/managed-by: kustomize
  name: releasedeployment-viewer-role
rules:
- apiGroups:
  - kuberik.com
  resources:
  - releasedeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberik.com
  resources:
  - releasedeployments/status
  verbs:
  - get
