# permissions for end users to edit releaseconstraints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: release-controller
    app.kubernetes.io/managed-by: kustomize
  name: releaseconstraint-editor-role
rules:
  - apiGroups:
      - kuberik.com
    resources:
      - releaseconstraints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kuberik.com
    resources:
      - releaseconstraints/status
    verbs:
      - get
