# permissions for end users to edit rolloutconstraints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rollout-controller
    app.kubernetes.io/managed-by: kustomize
  name: rolloutconstraint-editor-role
rules:
  - apiGroups:
      - kuberik.com
    resources:
      - rolloutconstraints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kuberik.com
    resources:
      - rolloutconstraints/status
    verbs:
      - get
