# permissions for end users to view rolloutgates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rollout-controller
    app.kubernetes.io/managed-by: kustomize
  name: rolloutgate-viewer-role
rules:
- apiGroups:
  - kuberik.com
  resources:
  - rolloutgates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberik.com
  resources:
  - rolloutgates/status
  verbs:
  - get
